### ISSUE TITLE
MEG - Cohérence mviewerstudio/mviewer

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#157]
> Issue développée dans le cadre d'une prestation JDev / Megalis Bretagne / GeoBretagne

## Histoire

**En tant que** utilisateur,
**Je souhaite** avoir les nouveaux paramètres mviewer dans l'interface mviewerstudio
**Pour** ne pas avoir à modifier la configuration XML et n'utiliser que l'interface mviewerstudio.

### Paramètres de l'application

|     PARAMETRE            |     COMPOSANT            |     CIBLE                   | Type   | Mode avancé  |
|--------------------------|--------------------------|-----------------------------|--------|--------|
|     Zoomtools            |     Checkbox             |     Onglet   Application    | bool   |  |
|     Initialextenttool    |     Checkbox             |     Onglet   Application    | bool   |  |
|     Titlehelp            |     Champ   text         |     Onglet   Application    | string | X |
|     Iconhelp             |     Bouton   + modale    |     Onglet   Application    | list   | X |
|     Geoloc               |     Checkbox             |     Onglet   Application    | bool   |  |
|     Mouseposition        |     Checkbox             |     Onglet   Application    | bool | X |
|     Studio               |     Champ   text         |     Onglet   Application    | string | X |
|     Home                 |     Champ   text         |     Onglet   Application    | string | X |
|     Favicon              |     Champ   text         |     Onglet   Application    | string | X |

### Paramètres de couche

| PARAMETRE            | COMPOSANT                | Cible                  | Type    | Mode avancé  |
|----------------------|--------------------------|------------------------|---------|--------|
|     Index            |     Champ   numérique    |     Couche / Onglet avancées / options d'affichage    | integer | X |
|     Styletitle       |     Champ   text         |     Couche / Onglet général    | string  |  |
|     dynamiclegend    |     Checkbox             |     Couche / Onglet avancées / options d'affichage    | bool    | X |
|     exclusive        |     Checkbox             |     Couche / Onglet avancées / options d'affichage    | bool    | X |
|     toplayer         |     Checkbox             |     Couche / Onglet général / options d'affichage    | bool    |  |
|     showintoc        |     Checkbox             |     Couche / Onglet avancées / options d'affichage    | bool    | X |

# Avancement

https://github.com/jdev-org/mviewerstudio/tree/issue-157

* Paramètres de l'application
* 
- [x] Zoomtools  - @Agath21 
- [x] Initialextenttool - @Agath21 
- [x] Titlehelp - @Agath21 
- [x] Iconhelp - @Agath21 
- [x] Geoloc - @Agath21 
- [x] Mouseposition - @Agath21 
- [x] Studio - @Agath21 
- [x] Home - @Agath21 
- [x] Favicon - @Agath21 

* Paramètres de couche

- [x] Index - @Gaetanbrl 
- [x] Styletitle - @Gaetanbrl 
- [x] dynamiclegend - @Gaetanbrl 
- [x] exclusive - @Gaetanbrl 
- [x] toplayer - @Gaetanbrl 
- [x] showintoc - @Gaetanbrl 

* Tous
- [x] Documentation associées aux paramètres - @Gaetanbrl @Agath21 
- [x] Mise à jour de la documentation mviewer avec le badge "studio" - @Gaetanbrl @Agath21
- [x] Revue des placeholder (les rendre + explicite)

### Bonus

- [x] [TMS en fond de plan](#172)
- [x] TMS en type de couche (#174 )
- [x] Enregistrer la version utilisée du studio dans le XML généré et la version cible du mviewer (#173 )

**Comment by spelhate** [comment]
On pourrait également enregistrer la version utilisée du studio dans le XML généré et la version cible du mviewer ?

**Comment by Gaetanbrl** [comment]
> On pourrait également enregistrer la version utilisée du studio dans le XML généré et la version cible du mviewer ?

Est-ce un paramètre supplémentaire de cette issue @spelhate ?

**Comment by Gaetanbrl** [comment]
@spelhate @lecault pouvez-vous compléter la colonne `Mode avancé` qui permet de définir quels sont les paramètres visibles en mode avancés et lesquels sont visibles en mode `simple` ?

**Comment by Gaetanbrl** [comment]
> pouvez-vous compléter la colonne Mode avancé

Complété en COTECH le 06/02/2023

**Comment by Agath21** [comment]
## Proposition technique - Ajout des fonctionnalités au sein de l'interface
### Module Application
![Studio2_applicationAddOptions](https://user-images.githubusercontent.com/22764056/217009694-f993c0d6-2aad-49b8-8b1e-5b51a375180f.png)

### Module Thématiques & données / Paramètres de la donnée / Onglet "Général"
![Studio2_dataGeneral](https://user-images.githubusercontent.com/22764056/217010270-513ca4b1-9234-424f-9e7f-d15eec157c68.png)

### Module Thématiques & données / Paramètres de la donnée / Onglet "Options avancées"
![Studio2_dataOptionsAvancees](https://user-images.githubusercontent.com/22764056/217018915-f1f172ee-25e0-4798-9dda-207bab852cb3.png)

**Gestion de la légende** :
- Ajout d'un nouvel accordéon pour la gestion de la légende avec la fonctionnalité "Légende statique" (fonctionnalité existante déplacée de "Options d'affichage") + `switch` de légende dynamique + Légende personnalisée (img)
- Ajout d'une liste déroulante pour le type de légende 
- Par défaut, c'est la légende geoserver issue du SLD
- Avec la valeur "personnalisée", le `switch` de la légende dynamique est remplacé par un `input` permettant d'indiquer un lien vers une image : 
![Studio2_legende_personnalisée](https://user-images.githubusercontent.com/22764056/217018856-ffcd7158-b850-4e0d-8acd-4f2e8a22277a.PNG)

**Comment by lecault** [comment]
Concernant la légende, peux on voit l'interface en mode normal ?

**Comment by Agath21** [comment]
@lecault Les paramètres liés à la légende étant situés dans l'onglet "Options avancées", ils ne sont pas accessibles / visibles en mode simple.
![image](https://user-images.githubusercontent.com/22764056/217197998-9fca2f8c-12be-4b54-b30c-0efbe9138eb0.png)

**Comment by lecault** [comment]
Ah d'accord. Je voulais voir l'affichage si type de légende <> personnalisée

**Comment by Agath21** [comment]
Désole, je n'avais pas compris ta demande. 

De base, c'est la légende geoserver avec le type de légende est "Par défaut". Seul l'option "Adapter la légende selon les données sur la carte" est disponible. Cette option correspond actuellement à la fonctionnalité "Légende dynamique" mais nous avons modifié l'intitulé que nous trouvions peu parlant. Le visuel est disponible dans mon commentaire avec les maquettes ou en zoom ci-dessous : 

![image](https://user-images.githubusercontent.com/22764056/217202683-1be80fb1-1ea6-4b97-b89c-fa6438392175.png)

**Comment by lecault** [comment]
Je reformulerai en "Adapter la légende selon le zoom de la carte"

**Comment by Agath21** [comment]
C'est noté, on se basera sur cet intitulé.

**Comment by lecault** [comment]
A moins que je n'ai pas anticipé d'autres usages @spelhate mais pour moi ça ne dépend que du zoom.

**Comment by Agath21** [comment]
## Identification d'un bug Mviewer | Options de l'application
### Description
Lorsque l'on ajoute les paramètres "`geoloc`" et "`studio`" dans la balise `application` du `config.xml`, il s'affiche constamment dans l'application malgré le changement de valeurs entre `false/true `. Pour les désactiver, il faut les supprimer totalement du `config.xml` 

![image](https://user-images.githubusercontent.com/22764056/217278678-441b1314-26fc-42b1-be58-bc89920ba0ab.png)

![image](https://user-images.githubusercontent.com/22764056/217278735-9081774f-e483-495d-bdbd-934dd068a304.png)

### Incidence sur le développement en cours
Les paramètres "`geoloc`" et "`studio`" sont déclarés et donc intégrés dans le `config.xml` généré par le studio. Les valeurs `false/true` changent en fonction des checkbox activées (ok > vérification du config généré et téléchargé). 

Toutefois, avec ce bug les deux fonctionnalités sont toujours activées dans les applications mviewer.

**Comment by Gaetanbrl** [comment]
> Identification d'un bug Mviewer 

@Agath21 :
- bug à reporter dans le bon dépôt 
- lien vers cette issue (ou commentaire précédent) à rajouter dans l'issue du bug

**Comment by spelhate** [comment]
> > On pourrait également enregistrer la version utilisée du studio dans le XML généré et la version cible du mviewer ?
> 
> Est-ce un paramètre supplémentaire de cette issue @spelhate ?

Il ne s'agit pas d'un paramètre, mais d'un attribut associé au config.xml exemple :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<config versionstudio="3.2">
```

**Comment by spelhate** [comment]
> A moins que je n'ai pas anticipé d'autres usages @spelhate mais pour moi ça ne dépend que du zoom.

Oui c'est bien ça.

**Comment by spelhate** [comment]
Il faudra également penser à mettre à jour la doc mviewer avec l'indication `studio` en face des paramètres concernés : 

![image](https://user-images.githubusercontent.com/1793792/217832775-ee2b6e32-9c3c-427e-9a7a-9be52978d937.png)
https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_app.html#parametres-principaux

**Comment by spelhate** [comment]
> > Identification d'un bug Mviewer
> 
> @Agath21 :
> 
>     * bug à reporter dans le bon dépôt
> 
>     * lien vers cette issue (ou commentaire précédent) à rajouter dans l'issue du bug

J'ai créé l'issue et la PR qui corrige le bug (https://github.com/mviewer/mviewer/pull/733)

**Comment by Gaetanbrl** [comment]
> J'ai créé l'issue et la PR qui corrige le bug

Super merci @spelhate

**Comment by Gaetanbrl** [comment]
Question sur la doc : 

Est-ce qu'on doit dupliquer la documentation ou bien on peut rediriger vers la bonne page de la doc mviewer qui défini déjà tous ces paramètres ?

**Comment by spelhate** [comment]
Pas besoin de dupliquer. On peut faire un lien comme tu le suggères.

**Comment by Agath21** [comment]
@spelhate sais-tu pourquoi un lien pointant vers l'université de bristol est présent dans les métadonnées des configs générés avec le studio ? 

`<rdf:Description rdf:about="http://www.ilrt.bristol.ac.uk/people/cmdjb/">`

Faut-il le conserver ?

**Comment by lecault** [comment]
> @spelhate sais-tu pourquoi un lien pointant vers l'université de bristol est présent dans les métadonnées des configs générés avec le studio ?
> 
> `<rdf:Description rdf:about="http://www.ilrt.bristol.ac.uk/people/cmdjb/">`
> 
> Faut-il le conserver ?

Alors là aucune idée d'où ça vient...

**Comment by lecault** [comment]
Merci pour le travail.

Mes remarques suite au test sur https://gis.jdev.fr/mviewerstudio/ : 

**Partie application** 

- Outils de zoom et Revenir à l'étendue initiale doivent être cochés par défaut
- Ne pas avoir dans la vue par défaut sur mviewer les bouton de géolocalisation et de modification sur studio
- Quand on active l'outil de mesure il apparaît 2 fois : 

![image](https://user-images.githubusercontent.com/5269430/220641188-123e8e2e-ac48-4d93-ba29-1bbad48f2ac5.png)

- Quand on bascule en mode avancé, je mettrai les liens vers la page principale et favicon sur la même ligne
- Dans l'ordre des fonctionnalités, en mode avancé Se géolocaliser doit avoir la même place qu'en mode simple (après l'export). D'ailleurs serai t'il judicieux d'avoir un ordre alphabétique : A-Z mode simple puis A-Z mode avancé ?
- Ouvrir dans studio ne fonctionne pas (peut être normal ?)
- Lien vers la page principale me parle pas. Je propose Lien vers site parent
- Dans lien vers la page principale si je met https://geobretagne.fr/ c'est en rouge pourquoi ?
- Ajout de fond de plan personnalisé : les tooltip sont indispensables (ex : différence entre Libellé et Titre)
- Ajout de fond de plan personnalisé ne fonctionne avec cet exemple en WMS. Je n'ai pas testé les autres types. Il semble y avoir un soucis avec les thumbmail (Uncaught TypeError: Cannot read properties of undefined (reading 'thumbgallery'))

![image](https://user-images.githubusercontent.com/5269430/220648198-dcbdb550-dcdc-42d5-9863-fa995e8eda37.png)

**Partie donnée**

- Je ne vois pas les styles disponibles
- Libellé de la liste des styles doit être affiché si au moins 2 styles sélectionnés
- Quand on va sur Options avancées je déplierai par défaut options d'affichage
- De manière générale, espacer un peu plus les checkbox 

![image](https://user-images.githubusercontent.com/5269430/220655576-de27ebd8-9f83-4823-a8ad-ffca9ee1011f.png)

Voilà pour moi

**Comment by Gaetanbrl** [comment]
@lecault est-ce que tu as une idée des placeholder que tu veux voir pour les champs ? Notamment ceux de l'ajout d'un fond personnalisé.

**Comment by Gaetanbrl** [comment]
> Ne pas avoir dans la vue par défaut sur mviewer les bouton de géolocalisation et de modification sur studio

@lecault il y a une PR de Sébastien en attente, il faut la valider pour qu'on puisse récupérer le correctif.

**Comment by lecault** [comment]
> > Ne pas avoir dans la vue par défaut sur mviewer les bouton de géolocalisation et de modification sur studio
> 
> @lecault il y a une PR de Sébastien en attente, il faut la valider pour qu'on puisse récupérer le correctif.

Elle est où ?

**Comment by Gaetanbrl** [comment]
> Elle est où ?

Dépôt mviewer : 

https://github.com/mviewer/mviewer/pull/733

Sinon j'ai testé `osm:map` et ca ne semble pas marcher dans mviewer :

```
        <baselayer visible="true" id="osm_map" 
			thumbgallery="https://geobretagne.fr/pub/logo/161_osmfr.jpg" title="osm map" label="OpenStreetMap 2 GéoBretagne" type="WMS" url="https://osm.geobretagne.fr/gwc01/service/wms" layers="osm:map" format="image/png" 
            attribution="GeoBretagne"/>
```

**Comment by Gaetanbrl** [comment]
> Sinon j'ai testé osm:map et ca ne semble pas marcher dans mviewer sans passer par studio:

Erratum ca marche (je testé pas le bon fichier)...

**Comment by lecault** [comment]
> @lecault est-ce que tu as une idée des placeholder que tu veux voir pour les champs ? Notamment ceux de l'ajout d'un fond personnalisé.

En regardant la doc https://mviewerdoc.readthedocs.io/fr/stable/doc_tech/config_baselayers.html je te propose :

Identifiant : ortho
Libellé : Orthophoto
Titre à renommer en Sous-Titre : Orthophotographie France (NOTE : ce champ me semble non indispensable dans mviewer)
Lien vers la vignette d'aperçu : https://mavignette.png
Attribution : IGN - Licence ouverte Etalab 2.0
URL ; https://wxs.ign.fr/essentiels/geoportail/wmts
Style : normal
Identifiant technique : ORTHOIMAGERY.ORTHOPHOTOS
Format image : est-ce que ça peut être bien de faire une liste déroulante avec image/jpeg et image/png ?

**Comment by lecault** [comment]
Pour la partie fond de plan je me rend compte que je sais pas à quoi sert le title ?
Je pense qu'il est inutile, à discuter mais c'est côté mviewer.

**Comment by Gaetanbrl** [comment]
> Je pense qu'il est inutile, à discuter mais c'est côté mviewer.

Idem, mais les paramètres ont été repris de mviewer. On ne fait qu'apporter la cohérence dans studio :)

**Comment by lecault** [comment]
On demandera à l'historique lundi :)

**Comment by lecault** [comment]
Tests effectuées sur la branche issue-157, voici mes remarques 

- [ ] Revenir à l'étendue initiale doit être coché par défaut
- [ ] Ordre des fonctionnalités à discuter avec @spelhate 
- [ ] Styletitle ne fonctionne pas
- [ ] Adapter la légende selon le zoom de la carte n'est pas conservé à l'enregistrement
- [ ] Se geolocalise : je n'ai pas pu vérifier => serveur de test sans https

**Comment by lecault** [comment]
Modification à faire suite au clic sur la maison car on ne quitte pas l'application studio.

Enregistrer mon application et retour à l'accueil
Ne pas enregistrer mes modifications et retour à l'accueil

![image](https://user-images.githubusercontent.com/5269430/224264255-71319a05-89c4-4032-b6d7-9b2161755a99.png)

**Comment by spelhate** [comment]
Bonjour. En complément, les tests réalisés ce matin sur la branche develop-meg

- [ ] Libellé info "Affichage exclusif de la donnée". Il faut préciser que ça concerne toutes les données de la carte **qui ont ce même paramétrage.**
- [ ] Remarque sur la couleur rouge des URL. Auparavant c'était rouge quand l'URL n'était pas valide et vert quand l'URL est valide est résolvable.
- [ ] Pas testé contraintes d'accès à la donnée.
- [ ] En activant lien vers studio mviewer l'URL vers studio est à "true" au lieu d'avoir l'url de studio.
- [ ] Résultat bizarre pour l'icone accueil (fab fa-apple) dans mviewer. Il faut une version de mviewer particulière ?

**Comment by Agath21** [comment]
Corrections réalisées : 

- [ ] Revenir à l'étendue initiale doit être coché par défaut
- [ ] Styletitle ne fonctionne pas

> Corrigé sur mviewer dans la PR 738


- [ ] Adapter la légende selon le zoom de la carte n'est pas conservé à l'enregistrement dans le XML
- [ ] Libellé info "Affichage exclusif de la donnée". Il faut préciser que ça concerne toutes les données de la carte qui ont ce même paramétrage.
- [ ] Remarque sur la couleur rouge des URL. Auparavant c'était rouge quand l'URL n'était pas valide et vert quand l'URL est valide est résolvable.
- [ ] En activant lien vers studio mviewer l'URL vers studio est à "true" au lieu d'avoir l'url de studio.
- [ ] Résultat bizarre pour l'icone accueil (fab fa-apple) dans mviewer. Il faut une version de mviewer particulière ?

> Problème lié à mviewer : `$("#iconhelp span").attr("class", "fa fa-" + conf.application.iconhelp); `

**Comment by Agath21** [comment]
Corrections disponibles sur la branche [develop-meg](https://github.com/jdev-org/mviewerstudio/tree/develop-meg)

**Comment by Agath21** [comment]
> Résultat bizarre pour l'icone accueil (fab fa-apple) dans mviewer. Il faut une version de mviewer particulière ?

Corrigé sur le dépôt mviewer avec la [PR #741](https://github.com/mviewer/mviewer/pull/741)

**Comment by lecault** [comment]
On est bon pour cette issue

**Comment by spelhate** [comment]
> On est bon pour cette issue

@lecault tu as pu tester avec une couche protégée ? De mon côté je n'ai pas qu'il faut.

**Comment by spelhate** [comment]
Sinon tout est ok pour moi également.

**Comment by lecault** [comment]
Remarque sur le bouton éditer dans studio. Il renvoie vers la page d'accueil du studio via une URL de ce type : http://test-sig5/mviewerstudio/index.html#http://test-sig5/mviewer/apps/store/39a9d224040f/preview/c505368e-c412-11ed-8811-00505698285b.xml

Il serait souhaitable d'arriver sur le studio avec les paramètres de l'appli chargée.

**Comment by lecault** [comment]
Suite à démo à mes collègues, une reformulation à faire :
Affichage de la donnée seulement sur la carte => Ne pas afficher la donnée dans la légende

**Comment by Agath21** [comment]
> Suite à démo à mes collègues, une reformulation à faire :
Affichage de la donnée seulement sur la carte => Ne pas afficher la donnée dans la légende

Ok, modifié ce jour
